### PR TITLE
chore: use ory-prettier-styles and add format check

### PR DESCRIPTION
**Pull request by zepatrik**

### CODE REVIEW

**Comment by aeneasr** [comment]
@zepatrik do you know if IntelliJ detects this prettier config?

**Comment by zepatrik** [comment]
It does for me, when I open `package.json` it asks me to use prettier for this project.

**Comment by aeneasr** [comment]
Do

```
npm i -g prettier
npm run format check
```

**Comment by zepatrik** [comment]
Using our hacky prettier install script from ory/ci now :wink: from 26s to 9s execution time :tada:

**Pull request merged**
